apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: my-validating-webhook
webhooks:
  - name: my-webhook.example.com
    clientConfig:
      service:
        name: podtato-head-entry
        namespace: default
        path: "/validate"
        port: 443
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    admissionReviewVersions: ["v1"]
    failurePolicy: Ignore
    sideEffects: None
